# Generated by Django 2.2.5 on 2019-12-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherindex',
            name='name',
            field=models.CharField(default='cold', max_length=30),
        ),
        migrations.AddField(
            model_name='weatherindex',
            name='next_page',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
