# Generated by Django 2.2.5 on 2019-12-02 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191203_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainWeatherIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cold', max_length=30)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_code', models.IntegerField()),
                ('disease_index', models.IntegerField()),
                ('next_page', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WeatherIndex',
        ),
    ]
