# Generated by Django 2.2.5 on 2019-12-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191203_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainweatherindex',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
