# Generated by Django 2.2.5 on 2019-12-02 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mainweatherindex_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsthmaIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_code', models.IntegerField()),
                ('disease_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ColdIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_code', models.IntegerField()),
                ('disease_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StrokeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_code', models.IntegerField()),
                ('disease_index', models.IntegerField()),
            ],
        ),
    ]
