# Generated by Django 2.2.5 on 2019-12-11 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_asthmaindex_coldindex_strokeindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asthmaindex',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coldindex',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='strokeindex',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
