# Generated by Django 2.2.5 on 2019-12-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191211_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asthmaindex',
            name='local_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coldindex',
            name='local_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='strokeindex',
            name='local_code',
            field=models.CharField(max_length=50),
        ),
    ]
