# Generated by Django 2.2.5 on 2019-12-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191211_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cold', max_length=30)),
                ('next_page', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
